version: '3.5'  

services: 
    frontend:
      container_name: frontend     
      image: frontend
      build: ./front            
      
    backend:      
      image: backend
      build: ./back
      restart: unless-stopped        
      environment:
        - REDIS=redis
        - DB_USERNAME=palmu
        - DB_PASSWORD=petri
        - DB_NAME=db_backend
        - DB_HOST=db
      depends_on: 
        - db
     
    redis:
      container_name: redis
      image: redis

    db:
      container_name: postgres_db
      image: postgres
      restart: unless-stopped
      environment:
        - POSTGRES_PASSWORD=petri
        - POSTGRES_USER=palmu
        - POSTGRES_DB=db_backend
      volumes:
        - database:/var/lib/postgresql/data
        
    nginx:
      container_name: nginx
      image: nginx
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
      ports:
        - 80:80
      depends_on: 
        - backend

volumes:
  database:

